### PR TITLE
fix the version and add the license to the package.json

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Comment by wkloucek** [comment]
@longsleep could you please have a look? The license info in the package.json makes it easier to perform license checks

**Comment by longsleep** [comment]
@wkloucek sure will take a look ASAP - is there any particular reason you guys still use Konnect and have not switched to it's vendor agnostic successor https://github.com/libregraph/lico ?

**Comment by longsleep** [comment]
> We should switch to https://github.com/libregraph/lico/blob/4c5f17e836263a62834d410ab1f00ab0a52cd14a/identifier/package.json then?

Yes, lico does not use kpop (as it is highly Kopano specific) - got removed here https://github.com/libregraph/lico/commit/a1f02df1a5bf089c3a2b6ebfe2ceb176461c9303

**Comment by longsleep** [comment]
Applied via https://stash.kopano.io/projects/KAPP/repos/kpop/commits/104a9584368ea589573d1d7c9a6ed19f70f24675#package.json

**Pull request closed without merging**
